name: Negar CI
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Define shot uid
        run: |
          COMMIT_SHORT_HASH=$(git rev-parse --short HEAD)
          echo "COMMIT_SHORT_HASH=$COMMIT_SHORT_HASH" >> $GITHUB_ENV

      - name: Deploy to stage
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli@5
          liara deploy --app="arvand" --api-token="$LIARA_TOKEN" --no-app-logs
